/**
 * categoriesData.js
 * ──────────────────
 * Master catalog of 150+ TaskLink categories grouped into logical domains.
 */

export const CATEGORY_GROUPS = [
  { id: 'all', label: 'All Categories' },
  { id: 'home', label: 'Home & Repair' },
  { id: 'tech', label: 'Tech & Digital' },
  { id: 'events', label: 'Events & Media' },
  { id: 'transport', label: 'Transport & Auto' },
  { id: 'wellness', label: 'Education & Care' },
  { id: 'business', label: 'Business & Legal' },
];

export const CATEGORIES = [
  // ── 1. Home & Maintenance (25) ──────────────────────────────────────────
  { id: 'cleaning', label: 'Cleaning', icon: 'sparkles-outline', group: 'home', color: '#0ea5e9' },
  { id: 'deepcleaning', label: 'Deep Cleaning', icon: 'brush-outline', group: 'home', color: '#0284c7' },
  { id: 'laundry', label: 'Laundry & Ironing', icon: 'shirt-outline', group: 'home', color: '#38bdf8' },
  { id: 'plumbing', label: 'Plumbing', icon: 'construct-outline', group: 'home', color: '#64748b' },
  { id: 'electrical', label: 'Electrical', icon: 'flash-outline', group: 'home', color: '#f59e0b' },
  { id: 'carpentry', label: 'Carpentry', icon: 'hammer-outline', group: 'home', color: '#b45309' },
  { id: 'painting', label: 'Painting', icon: 'color-palette-outline', group: 'home', color: '#ec4899' },
  { id: 'roofing', label: 'Roofing', icon: 'home-outline', group: 'home', color: '#78350f' },
  { id: 'tiling', label: 'Tiling & Flooring', icon: 'grid-outline', group: 'home', color: '#475569' },
  { id: 'gardening', label: 'Gardening & Lawn', icon: 'leaf-outline', group: 'home', color: '#22c55e' },
  { id: 'landscaping', label: 'Landscaping', icon: 'flower-outline', group: 'home', color: '#16a34a' },
  { id: 'pestcontrol', label: 'Pest Control', icon: 'bug-outline', group: 'home', color: '#dc2626' },
  { id: 'handyman', label: 'General Handyman', icon: 'build-outline', group: 'home', color: '#4f46e5' },
  { id: 'appliancerepair', label: 'Appliance Repair', icon: 'tv-outline', group: 'home', color: '#2563eb' },
  { id: 'acrepair', label: 'AC & HVAC Repair', icon: 'snow-outline', group: 'home', color: '#06b6d4' },
  { id: 'locksmith', label: 'Locksmith', icon: 'key-outline', group: 'home', color: '#d97706' },
  { id: 'glassrepair', label: 'Window & Glass', icon: 'square-outline', group: 'home', color: '#94a3b8' },
  { id: 'interior_design', label: 'Interior Design', icon: 'easel-outline', group: 'home', color: '#d946ef' },
  { id: 'fumigation', label: 'Fumigation', icon: 'flame-outline', group: 'home', color: '#ea580c' },
  { id: 'borehole', label: 'Water & Borehole', icon: 'water-outline', group: 'home', color: '#0284c7' },
  { id: 'solar', label: 'Solar Installation', icon: 'sunny-outline', group: 'home', color: '#eab308' },
  { id: 'welding', label: 'Welding & Metal', icon: 'hardware-chip-outline', group: 'home', color: '#52525b' },
  { id: 'masonry', label: 'Masonry & Concrete', icon: 'cube-outline', group: 'home', color: '#71717a' },
  { id: 'waste', label: 'Waste Removal', icon: 'trash-outline', group: 'home', color: '#65a30d' },
  { id: 'pool', label: 'Pool Cleaning', icon: 'boat-outline', group: 'home', color: '#0284c7' },

  // ── 2. Tech, Design & Digital (25) ──────────────────────────────────────
  { id: 'webdesign', label: 'Web Design', icon: 'desktop-outline', group: 'tech', color: '#6366f1' },
  { id: 'webdev', label: 'Web Development', icon: 'code-slash-outline', group: 'tech', color: '#4f46e5' },
  { id: 'mobiledev', label: 'App Development', icon: 'phone-portrait-outline', group: 'tech', color: '#4338ca' },
  { id: 'graphicdesign', label: 'Graphic Design', icon: 'color-filter-outline', group: 'tech', color: '#a855f7' },
  { id: 'logo_design', label: 'Logo & Branding', icon: 'shapes-outline', group: 'tech', color: '#9333ea' },
  { id: 'videoediting', label: 'Video Editing', icon: 'film-outline', group: 'tech', color: '#e11d48' },
  { id: 'animation', label: '2D/3D Animation', icon: 'play-circle-outline', group: 'tech', color: '#f43f5e' },
  { id: 'techsupport', label: 'Tech Support', icon: 'laptop-outline', group: 'tech', color: '#3b82f6' },
  { id: 'network', label: 'WiFi & Networking', icon: 'wifi-outline', group: 'tech', color: '#1d4ed8' },
  { id: 'cctv', label: 'CCTV & Security', icon: 'videocam-outline', group: 'tech', color: '#1e293b' },
  { id: 'softwaredev', label: 'Software Eng', icon: 'terminal-outline', group: 'tech', color: '#0f172a' },
  { id: 'seo', label: 'SEO & Growth', icon: 'trending-up-outline', group: 'tech', color: '#16a34a' },
  { id: 'socialmedia', label: 'Social Media Mgmt', icon: 'share-social-outline', group: 'tech', color: '#ec4899' },
  { id: 'copywriting', label: 'Copywriting', icon: 'document-text-outline', group: 'tech', color: '#8b5cf6' },
  { id: 'dataentry', label: 'Data Entry', icon: 'stats-chart-outline', group: 'tech', color: '#64748b' },
  { id: 'translation', label: 'Translation', icon: 'language-outline', group: 'tech', color: '#0ea5e9' },
  { id: 'transcription', label: 'Transcription', icon: 'mic-outline', group: 'tech', color: '#d97706' },
  { id: 'cybersecurity', label: 'Cybersecurity', icon: 'shield-checkmark-outline', group: 'tech', color: '#b91c1c' },
  { id: 'cloud', label: 'Cloud & DevOps', icon: 'cloud-upload-outline', group: 'tech', color: '#0284c7' },
  { id: 'ui_ux', label: 'UI/UX Design', icon: 'layers-outline', group: 'tech', color: '#7c3aed' },
  { id: 'cad', label: 'CAD & 3D Modeling', icon: 'cube-outline', group: 'tech', color: '#475569' },
  { id: 'game_dev', label: 'Game Development', icon: 'game-controller-outline', group: 'tech', color: '#16a34a' },
  { id: 'blockchain', label: 'Web3 & Crypto', icon: 'wallet-outline', group: 'tech', color: '#f59e0b' },
  { id: 'qa_testing', label: 'QA & Testing', icon: 'bug-outline', group: 'tech', color: '#10b981' },
  { id: 'hardware_repair', label: 'PC & Phone Repair', icon: 'hardware-chip-outline', group: 'tech', color: '#2563eb' },

  // ── 3. Events, Media & Beauty (25) ───────────────────────────────────────
  { id: 'photography', label: 'Photography', icon: 'camera-outline', group: 'events', color: '#ec4899' },
  { id: 'videography', label: 'Videography', icon: 'videocam-outline', group: 'events', color: '#f43f5e' },
  { id: 'dj', label: 'DJ Services', icon: 'disc-outline', group: 'events', color: '#8b5cf6' },
  { id: 'mc', label: 'Event MC / Host', icon: 'mic-outline', group: 'events', color: '#a855f7' },
  { id: 'catering', label: 'Catering Services', icon: 'restaurant-outline', group: 'events', color: '#ef4444' },
  { id: 'cake', label: 'Baking & Cakes', icon: 'cafe-outline', group: 'events', color: '#f472b6' },
  { id: 'eventplanning', label: 'Event Planning', icon: 'calendar-outline', group: 'events', color: '#6366f1' },
  { id: 'decor', label: 'Event Decoration', icon: 'sparkles-outline', group: 'events', color: '#d946ef' },
  { id: 'sound_lighting', label: 'Sound & Lighting', icon: 'bulb-outline', group: 'events', color: '#eab308' },
  { id: 'makeup', label: 'Makeup Artist', icon: 'brush-outline', group: 'events', color: '#f43f5e' },
  { id: 'hairstyling', label: 'Hair Styling', icon: 'cut-outline', group: 'events', color: '#a855f7' },
  { id: 'barber', label: 'Mobile Barber', icon: 'cut-outline', group: 'events', color: '#3b82f6' },
  { id: 'nailart', label: 'Nails & Manicure', icon: 'hand-left-outline', group: 'events', color: '#ec4899' },
  { id: 'tattoo', label: 'Tattoo & Piercing', icon: 'body-outline', group: 'events', color: '#171717' },
  { id: 'musician', label: 'Live Music / Band', icon: 'musical-notes-outline', group: 'events', color: '#7c3aed' },
  { id: 'florist', label: 'Floral Arrangement', icon: 'flower-outline', group: 'events', color: '#10b981' },
  { id: 'bouncers', label: 'Event Security', icon: 'shield-outline', group: 'events', color: '#334155' },
  { id: 'photo_booth', label: 'Photo Booth Rental', icon: 'images-outline', group: 'events', color: '#0284c7' },
  { id: 'mixology', label: 'Bartender & Drinks', icon: 'wine-outline', group: 'events', color: '#f59e0b' },
  { id: 'costume', label: 'Costume & Styling', icon: 'shirt-outline', group: 'events', color: '#c084fc' },
  { id: 'face_painting', label: 'Face Painting', icon: 'color-palette-outline', group: 'events', color: '#fbbf24' },
  { id: 'magic_clown', label: 'Party Entertainer', icon: 'happy-outline', group: 'events', color: '#fb923c' },
  { id: 'drone', label: 'Drone Coverage', icon: 'airplane-outline', group: 'events', color: '#0ea5e9' },
  { id: 'modeling', label: 'Modeling & Talent', icon: 'person-outline', group: 'events', color: '#e11d48' },
  { id: 'stage_setup', label: 'Stage & Tents', icon: 'home-outline', group: 'events', color: '#475569' },

  // ── 4. Transport, Moving & Auto (25) ─────────────────────────────────────
  { id: 'delivery', label: 'Parcel Delivery', icon: 'cube-outline', group: 'transport', color: '#f97316' },
  { id: 'moving', label: 'House Moving', icon: 'car-outline', group: 'transport', color: '#14b8a6' },
  { id: 'truck_hire', label: 'Truck & Lorry Hire', icon: 'bus-outline', group: 'transport', color: '#0d9488' },
  { id: 'driver', label: 'Personal Driver', icon: 'navigate-outline', group: 'transport', color: '#2563eb' },
  { id: 'car_wash', label: 'Mobile Car Wash', icon: 'water-outline', group: 'transport', color: '#0284c7' },
  { id: 'auto_mechanic', label: 'Auto Mechanic', icon: 'settings-outline', group: 'transport', color: '#ea580c' },
  { id: 'auto_electrician', label: 'Auto Electrician', icon: 'flash-outline', group: 'transport', color: '#eab308' },
  { id: 'car_towing', label: 'Car Towing', icon: 'warning-outline', group: 'transport', color: '#dc2626' },
  { id: 'bike_repair', label: 'Motorbike Repair', icon: 'bicycle-outline', group: 'transport', color: '#65a30d' },
  { id: 'car_detailing', label: 'Car Detailing', icon: 'sparkles-outline', group: 'transport', color: '#0ea5e9' },
  { id: 'windscreen', label: 'Windscreen Glass', icon: 'square-outline', group: 'transport', color: '#64748b' },
  { id: 'tyre_service', label: 'Tyre & Alignment', icon: 'disc-outline', group: 'transport', color: '#1e293b' },
  { id: 'boda', label: 'Boda Express', icon: 'speedometer-outline', group: 'transport', color: '#ef4444' },
  { id: 'errands', label: 'Errands & Shopping', icon: 'basket-outline', group: 'transport', color: '#8b5cf6' },
  { id: 'car_rental', label: 'Car Rental', icon: 'key-outline', group: 'transport', color: '#3b82f6' },
  { id: 'warehouse', label: 'Storage & Locker', icon: 'archive-outline', group: 'transport', color: '#b45309' },
  { id: 'cargo', label: 'Freight Cargo', icon: 'boat-outline', group: 'transport', color: '#0369a1' },
  { id: 'car_audio', label: 'Car Audio & Alarms', icon: 'volume-high-outline', group: 'transport', color: '#7c3aed' },
  { id: 'tinting', label: 'Window Tinting', icon: 'color-fill-outline', group: 'transport', color: '#334155' },
  { id: 'fleet', label: 'Fleet Logistics', icon: 'map-outline', group: 'transport', color: '#15803d' },
  { id: 'valet', label: 'Valet Parking', icon: 'car-sport-outline', group: 'transport', color: '#4f46e5' },
  { id: 'ambulance', label: 'Medical Transport', icon: 'medkit-outline', group: 'transport', color: '#e11d48' },
  { id: 'boat', label: 'Marine & Boat Repair', icon: 'boat-outline', group: 'transport', color: '#0284c7' },
  { id: 'heavy_equipment', label: 'Tractor & Digger', icon: 'construct-outline', group: 'transport', color: '#d97706' },
  { id: 'packing', label: 'Packing & Crate', icon: 'gift-outline', group: 'transport', color: '#854d0e' },

  // ── 5. Education, Wellness & Care (25) ──────────────────────────────────
  { id: 'tutoring', label: 'School Tutoring', icon: 'book-outline', group: 'wellness', color: '#8b5cf6' },
  { id: 'language_tutor', label: 'Language Coach', icon: 'chatbubbles-outline', group: 'wellness', color: '#7c3aed' },
  { id: 'music_lessons', label: 'Music Lessons', icon: 'musical-note-outline', group: 'wellness', color: '#6366f1' },
  { id: 'fitness', label: 'Personal Trainer', icon: 'fitness-outline', group: 'wellness', color: '#ef4444' },
  { id: 'yoga', label: 'Yoga & Wellness', icon: 'heart-outline', group: 'wellness', color: '#10b981' },
  { id: 'massage', label: 'Massage Therapist', icon: 'hand-right-outline', group: 'wellness', color: '#f472b6' },
  { id: 'cooking', label: 'Private Chef', icon: 'restaurant-outline', group: 'wellness', color: '#f97316' },
  { id: 'baking_class', label: 'Culinary Coach', icon: 'nutrition-outline', group: 'wellness', color: '#fb923c' },
  { id: 'petcare', label: 'Pet Grooming', icon: 'paw-outline', group: 'wellness', color: '#f59e0b' },
  { id: 'dogwalking', label: 'Dog Walking', icon: 'walk-outline', group: 'wellness', color: '#84cc16' },
  { id: 'vet', label: 'Veterinary Visit', icon: 'medkit-outline', group: 'wellness', color: '#06b6d4' },
  { id: 'babysitting', label: 'Nanny & Babysitter', icon: 'people-outline', group: 'wellness', color: '#ec4899' },
  { id: 'eldercare', label: 'Elderly Care', icon: 'medical-outline', group: 'wellness', color: '#3b82f6' },
  { id: 'househelp', label: 'Househelp Maid', icon: 'sparkles-outline', group: 'wellness', color: '#0ea5e9' },
  { id: 'counseling', label: 'Counseling & Therapy', icon: 'chatbox-ellipses-outline', group: 'wellness', color: '#a855f7' },
  { id: 'life_coach', label: 'Life Coach', icon: 'compass-outline', group: 'wellness', color: '#14b8a6' },
  { id: 'tailoring', label: 'Fashion Tailor', icon: 'cut-outline', group: 'wellness', color: '#e11d48' },
  { id: 'shoe_repair', label: 'Cobbler & Shoe Care', icon: 'footsteps-outline', group: 'wellness', color: '#78350f' },
  { id: 'swimming_coach', label: 'Swimming Coach', icon: 'water-outline', group: 'wellness', color: '#0284c7' },
  { id: 'sports_coach', label: 'Sports Coach', icon: 'trophy-outline', group: 'wellness', color: '#eab308' },
  { id: 'nutrition', label: 'Diet & Nutrition', icon: 'leaf-outline', group: 'wellness', color: '#22c55e' },
  { id: 'skincare', label: 'Spa & Skincare', icon: 'rose-outline', group: 'wellness', color: '#f43f5e' },
  { id: 'art_lessons', label: 'Art & Drawing', icon: 'easel-outline', group: 'wellness', color: '#d946ef' },
  { id: 'driving_instructor', label: 'Driving Lessons', icon: 'car-outline', group: 'wellness', color: '#2563eb' },
  { id: 'house_sitting', label: 'House Sitting', icon: 'home-outline', group: 'wellness', color: '#64748b' },

  // ── 6. Business, Legal & Professional (25) ──────────────────────────────
  { id: 'accounting', label: 'Accounting', icon: 'calculator-outline', group: 'business', color: '#0f172a' },
  { id: 'tax', label: 'Tax Consulting', icon: 'cash-outline', group: 'business', color: '#16a34a' },
  { id: 'legal', label: 'Legal Advice', icon: 'briefcase-outline', group: 'business', color: '#1e293b' },
  { id: 'hr', label: 'HR & Hiring', icon: 'people-circle-outline', group: 'business', color: '#4f46e5' },
  { id: 'business_plan', label: 'Business Plans', icon: 'document-attach-outline', group: 'business', color: '#2563eb' },
  { id: 'virtual_assistant', label: 'Virtual Assistant', icon: 'headset-outline', group: 'business', color: '#0ea5e9' },
  { id: 'auditing', label: 'Audit & Compliance', icon: 'checkmark-done-circle-outline', group: 'business', color: '#0284c7' },
  { id: 'branding', label: 'Brand Strategy', icon: 'ribbon-outline', group: 'business', color: '#7c3aed' },
  { id: 'grant_writing', label: 'Grant Writing', icon: 'create-outline', group: 'business', color: '#8b5cf6' },
  { id: 'research', label: 'Market Research', icon: 'search-circle-outline', group: 'business', color: '#d97706' },
  { id: 'typing', label: 'Document Typing', icon: 'print-outline', group: 'business', color: '#64748b' },
  { id: 'print_shop', label: 'Printing & Merch', icon: 'copy-outline', group: 'business', color: '#ea580c' },
  { id: 'notary', label: 'Notary Services', icon: 'shield-checkmark-outline', group: 'business', color: '#b91c1c' },
  { id: 'architecture', label: 'Architectural Plan', icon: 'business-outline', group: 'business', color: '#475569' },
  { id: 'surveyor', label: 'Land Surveying', icon: 'pin-outline', group: 'business', color: '#ca8a04' },
  { id: 'property_mgmt', label: 'Property Mgmt', icon: 'key-outline', group: 'business', color: '#059669' },
  { id: 'real_estate', label: 'Real Estate Agent', icon: 'home-outline', group: 'business', color: '#047857' },
  { id: 'insurance', label: 'Insurance Advisory', icon: 'umbrella-outline', group: 'business', color: '#0284c7' },
  { id: 'fundraising', label: 'Pitch & Capital', icon: 'bar-chart-outline', group: 'business', color: '#16a34a' },
  { id: 'public_relations', label: 'PR & Press Release', icon: 'megaphone-outline', group: 'business', color: '#e11d48' },
  { id: 'event_security', label: 'Private Guarding', icon: 'shield-outline', group: 'business', color: '#18181b' },
  { id: 'inventory', label: 'Stock Audit', icon: 'barcode-outline', group: 'business', color: '#52525b' },
  { id: 'tender_writing', label: 'Tender Bidding', icon: 'clipboard-outline', group: 'business', color: '#2563eb' },
  { id: 'iso_consulting', label: 'Quality Assurance', icon: 'ribbon-outline', group: 'business', color: '#059669' },
  { id: 'project_mgmt', label: 'Project Mgmt', icon: 'flag-outline', group: 'business', color: '#4338ca' },
];

export const CATEGORY_MAP = Object.fromEntries(
  CATEGORIES.map((c) => [c.id, c.label])
);
